### ISSUE TITLE
[please fix] no vanilla mobs spawning

### ISSUE THREAD

**Issue by PanAu9** [kreezxil/minecolonies-getting-started#13]
**Describe the bug**
I have a bit of a problem with the newest version of minecolonies. I just build a sweinherder and led 2 pigs into the inclosure however the swineherder seem to not notice these newly, more realistic pigs. Im going to try the same thing with chickens. And one more thing- when i tryed summoning normal vanilla pig via command or spawnegg it always wrote that i cannot siummon this entity

**Versions:**
 - Minecraft: 1.14.4
 - Forge: 28.1.30
 - Mod: 2.10.11

**Comment by kreezxil** [comment]
interesting, the new animals have a gestation period too, so breeding
mechanic is not even remotely compatible with minecolonies. I'll ask the
minecolonies team to add being compat with Genetic Animals to their todo
list.

**Comment by kreezxil** [comment]
I'll post a report the Genetic Animals Mod developer.

**Comment by kreezxil** [comment]
and that has been posted now at https://github.com/SaemonMoki/ExtendedAnimals/issues/7

@PanAu9 I did a test and I was able to spawn a pig.

If you're updating a server, you need to also copy my config files over.

look for eanimod-common.toml in the config folder and make sure that **general.spawnVanillaMobs** is enabled.

```toml
	[general.spawnVanillaMobs]
		#Set this to true to allow vanilla minecraft mobs to continue to spawn. False will prevent their spawning and only spawn Eanimod versions
		enabled = true
```
